### PR TITLE
Fix tag problem on Fabric

### PR DESCRIPTION
**Pull request by EvanHsieh0415**
`#forge:obsidian` -> `#c:obsidian`

### CODE REVIEW

**Comment by UnRealDinnerbone** [comment]
While this is an option, I think the best solution would be to make a new tag that contains both the c:obsidian and forge:obsidian tag as not have different recipes

**Comment by UnRealDinnerbone** [comment]
also what mod as c:obsidian

**Comment by EvanHsieh0415** [comment]
> While this is an option, I think the best solution would be to make a new tag that contains both the c:obsidian and forge:obsidian tag as not have different recipes

This is the method I use in my data pack: define a `c` tag and include both `c` and `forge` tags.
```json
// data/c/tags/items/obsidian.json
{
  "replace": false,
  "values": [
    "minecraft:obsidian",
    {
      "value": "#forge:obsidian",
      "required": false
    }
  ]
}
```

**Comment by EvanHsieh0415** [comment]
> also what mod as c:obsidian

Perhaps rare, but there are no Forge tags available for use in Fabric.

**Comment by UnRealDinnerbone** [comment]
I I will at fixing this just going to change it a bit

**Comment by EvanHsieh0415** [comment]
> also what mod as c:obsidian

I found it, the full name of c tag is convention tags, which is the tag implemented by fabric.
[FabricMC/fabric/fabric-convention-tags-v1](https://github.com/FabricMC/fabric/tree/1.20.1/fabric-convention-tags-v1)

**Comment by UnRealDinnerbone** [comment]
Yha I noticed that where it came from. I just removed the tag usage

**Pull request closed without merging**
